package cpu.opcodetypes.enums;

public enum OpCodeRegister {
	REGISTER_A,
	REGISTER_F,
	REGISTER_B,
	REGISTER_C,
	REGISTER_D,
	REGISTER_E,
	REGISTER_H,
	REGISTER_L,
	REGISTERS_HL,
	REGISTERS_SP,
	REGISTERS_BC,
	REGISTERS_DE,
	REGISTERS_AF,
	ADDRESS_HL,
	ADDRESS_BC,
	ADDRESS_DE,
	ADDRESS_HL_INC,
	ADDRESS_HL_DEC,
	ADDRESS_DATA_TO_A,
	ADDRESS_A_TO_DATA,
	ADDRESS_FF00_C,
	LDH_ADDRESS_FF00,
	LDH_ADDRESS_FF00_REGISTER_A,

}
